# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'diagnostic_plotter.ui'
#
# Created: Thu Sep  7 02:48:53 2017
#      by: PyQt4 UI code generator 4.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1286, 870)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.loadDataGroupBox = QtGui.QGroupBox(self.centralwidget)
        self.loadDataGroupBox.setGeometry(QtCore.QRect(1090, 20, 161, 81))
        self.loadDataGroupBox.setObjectName(_fromUtf8("loadDataGroupBox"))
        self.verticalLayoutWidget = QtGui.QWidget(self.loadDataGroupBox)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 20, 160, 61))
        self.verticalLayoutWidget.setObjectName(_fromUtf8("verticalLayoutWidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setSizeConstraint(QtGui.QLayout.SetNoConstraint)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.loadDataButton = QtGui.QPushButton(self.verticalLayoutWidget)
        self.loadDataButton.setObjectName(_fromUtf8("loadDataButton"))
        self.verticalLayout.addWidget(self.loadDataButton)
        self.dataSelectComboBox = QtGui.QComboBox(self.verticalLayoutWidget)
        self.dataSelectComboBox.setObjectName(_fromUtf8("dataSelectComboBox"))
        self.verticalLayout.addWidget(self.dataSelectComboBox)
        self.containerGroupBox = QtGui.QGroupBox(self.centralwidget)
        self.containerGroupBox.setGeometry(QtCore.QRect(870, 230, 391, 101))
        self.containerGroupBox.setObjectName(_fromUtf8("containerGroupBox"))
        self.gridLayoutWidget_2 = QtGui.QWidget(self.containerGroupBox)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(0, 20, 381, 74))
        self.gridLayoutWidget_2.setObjectName(_fromUtf8("gridLayoutWidget_2"))
        self.containerLayout = QtGui.QGridLayout(self.gridLayoutWidget_2)
        self.containerLayout.setMargin(0)
        self.containerLayout.setObjectName(_fromUtf8("containerLayout"))
        self.container_and_background_select = QtGui.QCheckBox(self.gridLayoutWidget_2)
        self.container_and_background_select.setObjectName(_fromUtf8("container_and_background_select"))
        self.containerLayout.addWidget(self.container_and_background_select, 0, 0, 1, 1)
        self.container_minus_background_select = QtGui.QCheckBox(self.gridLayoutWidget_2)
        self.container_minus_background_select.setObjectName(_fromUtf8("container_minus_background_select"))
        self.containerLayout.addWidget(self.container_minus_background_select, 1, 0, 1, 1)
        self.container_background_select = QtGui.QCheckBox(self.gridLayoutWidget_2)
        self.container_background_select.setObjectName(_fromUtf8("container_background_select"))
        self.containerLayout.addWidget(self.container_background_select, 2, 0, 1, 1)
        self.container_and_background_normalized_select = QtGui.QCheckBox(self.gridLayoutWidget_2)
        self.container_and_background_normalized_select.setObjectName(_fromUtf8("container_and_background_normalized_select"))
        self.containerLayout.addWidget(self.container_and_background_normalized_select, 0, 1, 1, 1)
        self.container_normalized = QtGui.QCheckBox(self.gridLayoutWidget_2)
        self.container_normalized.setObjectName(_fromUtf8("container_normalized"))
        self.containerLayout.addWidget(self.container_normalized, 1, 1, 1, 1)
        self.container_background_normalized = QtGui.QCheckBox(self.gridLayoutWidget_2)
        self.container_background_normalized.setObjectName(_fromUtf8("container_background_normalized"))
        self.containerLayout.addWidget(self.container_background_normalized, 2, 1, 1, 1)
        self.vanadiumGroupBox = QtGui.QGroupBox(self.centralwidget)
        self.vanadiumGroupBox.setGeometry(QtCore.QRect(870, 341, 391, 171))
        self.vanadiumGroupBox.setObjectName(_fromUtf8("vanadiumGroupBox"))
        self.gridLayoutWidget_3 = QtGui.QWidget(self.vanadiumGroupBox)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(0, 20, 381, 131))
        self.gridLayoutWidget_3.setObjectName(_fromUtf8("gridLayoutWidget_3"))
        self.vanadiumLayout = QtGui.QGridLayout(self.gridLayoutWidget_3)
        self.vanadiumLayout.setMargin(0)
        self.vanadiumLayout.setObjectName(_fromUtf8("vanadiumLayout"))
        self.vanadium_minus_background_ms_abs_corr_stripped_smoothed_select = QtGui.QCheckBox(self.gridLayoutWidget_3)
        self.vanadium_minus_background_ms_abs_corr_stripped_smoothed_select.setObjectName(_fromUtf8("vanadium_minus_background_ms_abs_corr_stripped_smoothed_select"))
        self.vanadiumLayout.addWidget(self.vanadium_minus_background_ms_abs_corr_stripped_smoothed_select, 1, 1, 1, 1)
        self.vanadium_background_normalized_select = QtGui.QCheckBox(self.gridLayoutWidget_3)
        self.vanadium_background_normalized_select.setObjectName(_fromUtf8("vanadium_background_normalized_select"))
        self.vanadiumLayout.addWidget(self.vanadium_background_normalized_select, 3, 0, 1, 1)
        self.vanadium_and_background_select = QtGui.QCheckBox(self.gridLayoutWidget_3)
        self.vanadium_and_background_select.setObjectName(_fromUtf8("vanadium_and_background_select"))
        self.vanadiumLayout.addWidget(self.vanadium_and_background_select, 0, 0, 1, 1)
        self.vanadium_minus_background_select = QtGui.QCheckBox(self.gridLayoutWidget_3)
        self.vanadium_minus_background_select.setObjectName(_fromUtf8("vanadium_minus_background_select"))
        self.vanadiumLayout.addWidget(self.vanadium_minus_background_select, 1, 0, 1, 1)
        self.vanadium_background_select = QtGui.QCheckBox(self.gridLayoutWidget_3)
        self.vanadium_background_select.setObjectName(_fromUtf8("vanadium_background_select"))
        self.vanadiumLayout.addWidget(self.vanadium_background_select, 2, 0, 1, 1)
        self.vanadium_minus_background_ms_abs_corr_stripped_select = QtGui.QCheckBox(self.gridLayoutWidget_3)
        self.vanadium_minus_background_ms_abs_corr_stripped_select.setObjectName(_fromUtf8("vanadium_minus_background_ms_abs_corr_stripped_select"))
        self.vanadiumLayout.addWidget(self.vanadium_minus_background_ms_abs_corr_stripped_select, 0, 1, 1, 1)
        self.vanadium_placzek_correction_select = QtGui.QCheckBox(self.gridLayoutWidget_3)
        self.vanadium_placzek_correction_select.setObjectName(_fromUtf8("vanadium_placzek_correction_select"))
        self.vanadiumLayout.addWidget(self.vanadium_placzek_correction_select, 2, 1, 1, 1)
        self.vanadium_minus_background_ms_abs_corr_stripped_smoothed_placzek_select = QtGui.QCheckBox(self.gridLayoutWidget_3)
        self.vanadium_minus_background_ms_abs_corr_stripped_smoothed_placzek_select.setObjectName(_fromUtf8("vanadium_minus_background_ms_abs_corr_stripped_smoothed_placzek_select"))
        self.vanadiumLayout.addWidget(self.vanadium_minus_background_ms_abs_corr_stripped_smoothed_placzek_select, 3, 1, 1, 1)
        self.vanadium_minus_background_ms_abs_corr_select = QtGui.QCheckBox(self.gridLayoutWidget_3)
        self.vanadium_minus_background_ms_abs_corr_select.setObjectName(_fromUtf8("vanadium_minus_background_ms_abs_corr_select"))
        self.vanadiumLayout.addWidget(self.vanadium_minus_background_ms_abs_corr_select, 4, 0, 1, 1)
        self.sampleGroupBox = QtGui.QGroupBox(self.centralwidget)
        self.sampleGroupBox.setGeometry(QtCore.QRect(870, 511, 401, 181))
        self.sampleGroupBox.setObjectName(_fromUtf8("sampleGroupBox"))
        self.gridLayoutWidget_4 = QtGui.QWidget(self.sampleGroupBox)
        self.gridLayoutWidget_4.setGeometry(QtCore.QRect(0, 20, 391, 152))
        self.gridLayoutWidget_4.setObjectName(_fromUtf8("gridLayoutWidget_4"))
        self.sampleLayout = QtGui.QGridLayout(self.gridLayoutWidget_4)
        self.sampleLayout.setMargin(0)
        self.sampleLayout.setObjectName(_fromUtf8("sampleLayout"))
        self.sample_minus_background_normalized_ms_abs_corr_norm_by_atoms_sigma_v_select = QtGui.QCheckBox(self.gridLayoutWidget_4)
        self.sample_minus_background_normalized_ms_abs_corr_norm_by_atoms_sigma_v_select.setObjectName(_fromUtf8("sample_minus_background_normalized_ms_abs_corr_norm_by_atoms_sigma_v_select"))
        self.sampleLayout.addWidget(self.sample_minus_background_normalized_ms_abs_corr_norm_by_atoms_sigma_v_select, 1, 1, 1, 1)
        self.sample_normalized_select = QtGui.QCheckBox(self.gridLayoutWidget_4)
        self.sample_normalized_select.setObjectName(_fromUtf8("sample_normalized_select"))
        self.sampleLayout.addWidget(self.sample_normalized_select, 3, 0, 1, 1)
        self.sample_and_background_select = QtGui.QCheckBox(self.gridLayoutWidget_4)
        self.sample_and_background_select.setObjectName(_fromUtf8("sample_and_background_select"))
        self.sampleLayout.addWidget(self.sample_and_background_select, 0, 0, 1, 1)
        self.sample_minus_background_select = QtGui.QCheckBox(self.gridLayoutWidget_4)
        self.sample_minus_background_select.setObjectName(_fromUtf8("sample_minus_background_select"))
        self.sampleLayout.addWidget(self.sample_minus_background_select, 1, 0, 1, 1)
        self.sample_and_background_normalized_select = QtGui.QCheckBox(self.gridLayoutWidget_4)
        self.sample_and_background_normalized_select.setObjectName(_fromUtf8("sample_and_background_normalized_select"))
        self.sampleLayout.addWidget(self.sample_and_background_normalized_select, 2, 0, 1, 1)
        self.sample_minus_background_normalized_ms_abs_corr_norm_by_atoms_select = QtGui.QCheckBox(self.gridLayoutWidget_4)
        self.sample_minus_background_normalized_ms_abs_corr_norm_by_atoms_select.setObjectName(_fromUtf8("sample_minus_background_normalized_ms_abs_corr_norm_by_atoms_select"))
        self.sampleLayout.addWidget(self.sample_minus_background_normalized_ms_abs_corr_norm_by_atoms_select, 0, 1, 1, 1)
        self.sample_placzek_correction = QtGui.QCheckBox(self.gridLayoutWidget_4)
        self.sample_placzek_correction.setObjectName(_fromUtf8("sample_placzek_correction"))
        self.sampleLayout.addWidget(self.sample_placzek_correction, 2, 1, 1, 1)
        self.sample_minus_background_normalized_ms_abs_corr_norm_by_atoms_sigma_v_placzek_select = QtGui.QCheckBox(self.gridLayoutWidget_4)
        self.sample_minus_background_normalized_ms_abs_corr_norm_by_atoms_sigma_v_placzek_select.setObjectName(_fromUtf8("sample_minus_background_normalized_ms_abs_corr_norm_by_atoms_sigma_v_placzek_select"))
        self.sampleLayout.addWidget(self.sample_minus_background_normalized_ms_abs_corr_norm_by_atoms_sigma_v_placzek_select, 3, 1, 1, 1)
        self.sample_minus_background_normalized_ms_abs_corr_select = QtGui.QCheckBox(self.gridLayoutWidget_4)
        self.sample_minus_background_normalized_ms_abs_corr_select.setObjectName(_fromUtf8("sample_minus_background_normalized_ms_abs_corr_select"))
        self.sampleLayout.addWidget(self.sample_minus_background_normalized_ms_abs_corr_select, 4, 0, 1, 1)
        self.sofq_select = QtGui.QCheckBox(self.gridLayoutWidget_4)
        self.sofq_select.setObjectName(_fromUtf8("sofq_select"))
        self.sampleLayout.addWidget(self.sofq_select, 5, 0, 1, 1)
        self.fofq_select = QtGui.QCheckBox(self.gridLayoutWidget_4)
        self.fofq_select.setObjectName(_fromUtf8("fofq_select"))
        self.sampleLayout.addWidget(self.fofq_select, 5, 1, 1, 1)
        self.bankSelectionGroupBox = QtGui.QGroupBox(self.centralwidget)
        self.bankSelectionGroupBox.setGeometry(QtCore.QRect(870, 109, 381, 101))
        self.bankSelectionGroupBox.setObjectName(_fromUtf8("bankSelectionGroupBox"))
        self.gridLayoutWidget_5 = QtGui.QWidget(self.bankSelectionGroupBox)
        self.gridLayoutWidget_5.setGeometry(QtCore.QRect(10, 20, 361, 74))
        self.gridLayoutWidget_5.setObjectName(_fromUtf8("gridLayoutWidget_5"))
        self.gridLayout_5 = QtGui.QGridLayout(self.gridLayoutWidget_5)
        self.gridLayout_5.setMargin(0)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.bank1_select = QtGui.QCheckBox(self.gridLayoutWidget_5)
        self.bank1_select.setObjectName(_fromUtf8("bank1_select"))
        self.gridLayout_5.addWidget(self.bank1_select, 0, 0, 1, 1)
        self.bank2_select = QtGui.QCheckBox(self.gridLayoutWidget_5)
        self.bank2_select.setObjectName(_fromUtf8("bank2_select"))
        self.gridLayout_5.addWidget(self.bank2_select, 1, 0, 1, 1)
        self.bank3_select = QtGui.QCheckBox(self.gridLayoutWidget_5)
        self.bank3_select.setObjectName(_fromUtf8("bank3_select"))
        self.gridLayout_5.addWidget(self.bank3_select, 2, 0, 1, 1)
        self.bank4_select = QtGui.QCheckBox(self.gridLayoutWidget_5)
        self.bank4_select.setObjectName(_fromUtf8("bank4_select"))
        self.gridLayout_5.addWidget(self.bank4_select, 0, 1, 1, 1)
        self.bank5_select = QtGui.QCheckBox(self.gridLayoutWidget_5)
        self.bank5_select.setObjectName(_fromUtf8("bank5_select"))
        self.gridLayout_5.addWidget(self.bank5_select, 1, 1, 1, 1)
        self.bank6_select = QtGui.QCheckBox(self.gridLayoutWidget_5)
        self.bank6_select.setObjectName(_fromUtf8("bank6_select"))
        self.gridLayout_5.addWidget(self.bank6_select, 2, 1, 1, 1)
        self.canvasWidget = QtGui.QWidget(self.centralwidget)
        self.canvasWidget.setGeometry(QtCore.QRect(10, 10, 851, 661))
        self.canvasWidget.setObjectName(_fromUtf8("canvasWidget"))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1286, 20))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.adjustDataDock = QtGui.QDockWidget(MainWindow)
        self.adjustDataDock.setObjectName(_fromUtf8("adjustDataDock"))
        self.dockWidgetContents = QtGui.QWidget()
        self.dockWidgetContents.setObjectName(_fromUtf8("dockWidgetContents"))
        self.adjustDataGroupBox = QtGui.QGroupBox(self.dockWidgetContents)
        self.adjustDataGroupBox.setGeometry(QtCore.QRect(9, -1, 381, 101))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.adjustDataGroupBox.sizePolicy().hasHeightForWidth())
        self.adjustDataGroupBox.setSizePolicy(sizePolicy)
        self.adjustDataGroupBox.setObjectName(_fromUtf8("adjustDataGroupBox"))
        self.gridLayoutWidget = QtGui.QWidget(self.adjustDataGroupBox)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(0, 20, 381, 80))
        self.gridLayoutWidget.setObjectName(_fromUtf8("gridLayoutWidget"))
        self.adjustDataLayout = QtGui.QGridLayout(self.gridLayoutWidget)
        self.adjustDataLayout.setMargin(0)
        self.adjustDataLayout.setObjectName(_fromUtf8("adjustDataLayout"))
        self.scaleSlider = QtGui.QSlider(self.gridLayoutWidget)
        self.scaleSlider.setOrientation(QtCore.Qt.Horizontal)
        self.scaleSlider.setObjectName(_fromUtf8("scaleSlider"))
        self.adjustDataLayout.addWidget(self.scaleSlider, 1, 0, 1, 1)
        self.scaleLabel = QtGui.QLabel(self.gridLayoutWidget)
        self.scaleLabel.setObjectName(_fromUtf8("scaleLabel"))
        self.adjustDataLayout.addWidget(self.scaleLabel, 0, 0, 1, 1)
        self.shiftLabel = QtGui.QLabel(self.gridLayoutWidget)
        self.shiftLabel.setObjectName(_fromUtf8("shiftLabel"))
        self.adjustDataLayout.addWidget(self.shiftLabel, 0, 1, 1, 1)
        self.shiftSlider = QtGui.QSlider(self.gridLayoutWidget)
        self.shiftSlider.setOrientation(QtCore.Qt.Horizontal)
        self.shiftSlider.setObjectName(_fromUtf8("shiftSlider"))
        self.adjustDataLayout.addWidget(self.shiftSlider, 1, 1, 1, 1)
        self.adjustDataDock.setWidget(self.dockWidgetContents)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(8), self.adjustDataDock)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.loadDataGroupBox.setTitle(_translate("MainWindow", "Load Data", None))
        self.loadDataButton.setText(_translate("MainWindow", "Load", None))
        self.containerGroupBox.setTitle(_translate("MainWindow", "Container", None))
        self.container_and_background_select.setText(_translate("MainWindow", "C+Bc", None))
        self.container_minus_background_select.setText(_translate("MainWindow", "C", None))
        self.container_background_select.setText(_translate("MainWindow", "Bc", None))
        self.container_and_background_normalized_select.setText(_translate("MainWindow", "C+Bc / V", None))
        self.container_normalized.setText(_translate("MainWindow", "C / V", None))
        self.container_background_normalized.setText(_translate("MainWindow", "Bc / V", None))
        self.vanadiumGroupBox.setTitle(_translate("MainWindow", "Vanadium", None))
        self.vanadium_minus_background_ms_abs_corr_stripped_smoothed_select.setText(_translate("MainWindow", "1/Avv * V(stripped, smoothed)", None))
        self.vanadium_background_normalized_select.setText(_translate("MainWindow", "Bv / V", None))
        self.vanadium_and_background_select.setText(_translate("MainWindow", "V+Bv", None))
        self.vanadium_minus_background_select.setText(_translate("MainWindow", "V", None))
        self.vanadium_background_select.setText(_translate("MainWindow", "Bv", None))
        self.vanadium_minus_background_ms_abs_corr_stripped_select.setText(_translate("MainWindow", "1/Avv * V (stripped)", None))
        self.vanadium_placzek_correction_select.setText(_translate("MainWindow", "V placzek correction", None))
        self.vanadium_minus_background_ms_abs_corr_stripped_smoothed_placzek_select.setText(_translate("MainWindow", "1/Avv * V ( stripped, smoothed, placzek", None))
        self.vanadium_minus_background_ms_abs_corr_select.setText(_translate("MainWindow", "1/Avv * V", None))
        self.sampleGroupBox.setTitle(_translate("MainWindow", "Sample", None))
        self.sample_minus_background_normalized_ms_abs_corr_norm_by_atoms_sigma_v_select.setText(_translate("MainWindow", "Ns/Nv * 1/As * S/V * sigma_v", None))
        self.sample_normalized_select.setText(_translate("MainWindow", "S / V", None))
        self.sample_and_background_select.setText(_translate("MainWindow", "S+C+Bc", None))
        self.sample_minus_background_select.setText(_translate("MainWindow", "S", None))
        self.sample_and_background_normalized_select.setText(_translate("MainWindow", "S+C+Bc / V", None))
        self.sample_minus_background_normalized_ms_abs_corr_norm_by_atoms_select.setText(_translate("MainWindow", "Ns/Nv * 1/As * S/V", None))
        self.sample_placzek_correction.setText(_translate("MainWindow", "S placzek correction", None))
        self.sample_minus_background_normalized_ms_abs_corr_norm_by_atoms_sigma_v_placzek_select.setText(_translate("MainWindow", "Ns/Nv * 1/As * S/V * sigma_v (placzek)", None))
        self.sample_minus_background_normalized_ms_abs_corr_select.setText(_translate("MainWindow", "1/As * S/V", None))
        self.sofq_select.setText(_translate("MainWindow", "S(Q)", None))
        self.fofq_select.setText(_translate("MainWindow", "F(Q)", None))
        self.bankSelectionGroupBox.setTitle(_translate("MainWindow", "Bank Selection", None))
        self.bank1_select.setText(_translate("MainWindow", "Bank 1 (7 deg)", None))
        self.bank2_select.setText(_translate("MainWindow", "Bank 2 (15 deg)", None))
        self.bank3_select.setText(_translate("MainWindow", "Bank 3 (31 deg)", None))
        self.bank4_select.setText(_translate("MainWindow", "Bank 4 (67 deg)", None))
        self.bank5_select.setText(_translate("MainWindow", "Bank 5 (122 deg)", None))
        self.bank6_select.setText(_translate("MainWindow", "Bank 6 (154 deg)", None))
        self.adjustDataGroupBox.setTitle(_translate("MainWindow", "Adjust Data", None))
        self.scaleLabel.setText(_translate("MainWindow", "Scale", None))
        self.shiftLabel.setText(_translate("MainWindow", "Shift", None))

